# MOS custom: Suppress smart syslog messages (Temperature, resuming checks)  
if $programname == 'smartd' and $msg contains 'Temperature' then stop
if $programname == 'smartd' and $msg contains 'resuming checks' then stop
