#!/bin/sh

### BEGIN INIT INFO
# Provides:          mos-api
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the mos-api
# Description:       starts mos-api using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON="/usr/bin/node"
ARGS="src/index.js"
NAME="mos-api"
DESC="mos-api"
USER="root"

DIRECTORY="/usr/local/lib/mos-api"
PID="/run/mos-api.pid"

. /lib/init/vars.sh
. /lib/lsb/init-functions

# Import MOS functions
. /usr/local/lib/functions/mos-common

# Set node module location
export NODE_PATH=/usr/local/lib/mos-api-node_modules

# MOS custom: Pull latest version from mos-api
download_mosapi() {
  # Set GH_AUTH
  GH_TOKEN=$(jq -r '.github // empty' /boot/config/system/tokens.json)
  if [ ! -z "$GH_TOKEN" ] ; then
    TOKEN="$(decrypt_password "$GH_TOKEN" "tokens")"
    GH_AUTH="oauth2:$TOKEN@"
  else
    GH_AUTH=""
  fi

  if [ "$(ls -A /usr/local/lib/mos-api 2>/dev/null)" ] ; then
    rm -rf /usr/local/lib/mos-api/* /usr/local/lib/mos-api/.* 2>/dev/null
  fi
  if [ ! -d /usr/local/lib/mos-api ] ; then
    mkdir -p /usr/local/lib/mos-api
  fi
  cd /usr/local/lib/mos-api
  git clone https://${GH_AUTH}github.com/ich777/mos-api.git --depth=1 . >/dev/null 2>&1
  API_V=$(date -d @"$(git -C /usr/local/lib/mos-api log -1 --format=%ct)" "+%Y%m%d-%H%M")
  jq --arg api_v "${API_V}_updated" '.mos.api = $api_v' /etc/mos-release.json > /etc/mos-release.json.tmp && mv /etc/mos-release.json.tmp /etc/mos-release.json
  rm -rf /usr/local/lib/mos-api/node_modules /usr/local/lib/mos-api/package-lock.json
}

start_mosapi() {
  start-stop-daemon --start --background --make-pidfile --pidfile $PID \
    --chdir "$DIRECTORY" --user $USER --exec "$DAEMON" --output /var/log/api -- $ARGS >/dev/null 2>&1
}

stop_mosapi() {
  start-stop-daemon --stop --pidfile "$PID"
}

case "$1" in
  start)
    log_daemon_msg "Starting $DESC" "$NAME"
    start_mosapi
    case "$?" in
      0|1) log_end_msg 0 ;;
      2)   log_end_msg 1 ;;
    esac
  ;;
  stop)
    log_daemon_msg "Stopping $DESC" "$NAME"
    stop_mosapi
    case "$?" in
      0|1) log_end_msg 0 ;;
      2)   log_end_msg 1 ;;
    esac
  ;;
  restart)
    log_daemon_msg "Restarting $DESC" "$NAME"

    stop_mosapi
    case "$?" in
      0|1)
        download_mosapi
        start_mosapi
        case "$?" in
          0) log_end_msg 0 ;;
          1) log_end_msg 1 ;; # Old process is still running
          *) log_end_msg 1 ;; # Failed to start
        esac
      ;;
      *)
        # Failed to stop
        log_end_msg 1
      ;;
    esac
  ;;
  update)
    log_daemon_msg "Updating mos-api" "$NAME"

    stop_mosapi
    case "$?" in
      0|1)
        download_mosapi
        start_mosapi
        case "$?" in
          0) log_end_msg 0 ;;
          1) log_end_msg 1 ;; # Old process is still running
          *) log_end_msg 1 ;; # Failed to start
        esac
      ;;
      *)
        # Failed to stop
        log_end_msg 1
      ;;
    esac
  ;;
  status)
    status_of_proc -p $PID "$DAEMON" "$NAME" && exit 0 || exit $?
  ;;
  *)
    echo "Usage: $NAME {start|stop|restart|update|status}" >&2
    exit 3
  ;;
esac
