#!/bin/sh -e
# MOS custom

### BEGIN INIT INFO
# Provides:          notify
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Run mos-notfiy
# Description:       Run mos-notfiy
### END INIT INFO

PATH="/sbin:/bin:/usr/sbin:/usr/bin"
DAEMON="/usr/bin/mos-notify"
DESC="MOS Notify"
NAME="mos-notify"
USER="root"

if [ "$DEBUG" = "true" ] ; then
  DEBUG_ARG="--output /var/log/notify"
  if [ "$VERBOSE" = "true" ] ; then
    DAEMON="$DAEMON --verbose"
  fi
else
  DEBUG_ARG=""
fi

PID="/run/mos-notify.pid"
PERSIST_NOTIFICATIONS=$(jq -r '.persist_notifications // false' /boot/config/system.json 2>/dev/null)

. /lib/init/vars.sh
. /lib/lsb/init-functions

start_notify() {
  if [ "$PERSIST_NOTIFICATIONS" = "true" ] ; then
    if [ -f /boot/config/notify/notifications.json ] ; then
      mkdir -p /var/mos/notify 2>/dev/null
      cp /boot/config/notify/notifications.json /var/mos/notify/notifications.json
    fi
  fi
  start-stop-daemon --start --background --make-pidfile --pidfile $PID \
    --user $USER --exec "$DAEMON" $DEBUG_ARG -- $ARGS >/dev/null 2>&1

  # Remove ports.json file (should be removed in the future)
  if [ "/boot/config/notify/ports.json" ] ; then
    rm -f /boot/config/notify/ports.json
  fi
}

stop_notify() {
  if [ "$PERSIST_NOTIFICATIONS" = "true" ] ; then
    if [ -f /var/mos/notify/notifications.json ] ; then
      cp /var/mos/notify/notifications.json /boot/config/notify/notifications.json
    fi
  fi
  start-stop-daemon --stop --pidfile "$PID"
  rm -f /run/mos-notify.sock
}

case "$1" in
  start)
    log_daemon_msg "Starting $DESC" "$NAME"
    start_notify
    log_end_msg 0
  ;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
    stop_notify
    log_end_msg 0
  ;;
  restart)
	log_daemon_msg "Restarting $DESC" "$NAME"
    stop_notify
	sleep 1
	start_notify
    log_end_msg 0
  ;;
esac
