#!/bin/sh

### BEGIN INIT INFO
# Provides:        ntpsec
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start NTP daemon
# Description:       NTP, the Network Time Protocol, is used to keep computer
#                    clocks accurate by synchronizing them over the Internet or
#                    a local network, or by following an accurate hardware
#                    receiver that interprets GPS, DCF-77, or similar time
#                    signals.
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON=/usr/sbin/ntpd
PIDFILE=/run/ntpd.pid

test -x $DAEMON || exit 5

# MOS Custom: Make sure that log directory exists
[ ! -d /var/log/ntpsec ] && \
  mkdir -p /var/log/ntpsec
chown -R ntpsec:ntpsec /var/log/ntpsec 2>/dev/null

if [ -r /etc/default/ntpsec ] ; then
  . /etc/default/ntpsec
fi

if [ "$IGNORE_DHCP" != "yes" ] && [ -e /run/ntpsec/ntp.conf.dhcp ] ; then
  NTPD_OPTS="$NTPD_OPTS -c /run/ntpsec/ntp.conf.dhcp"
else
  # List the default -c first, so if the admin has specified -c in
  # NTPD_OPTS, it is honored.
  NTPD_OPTS="-c /etc/ntpsec/ntp.conf $NTPD_OPTS"
fi

NTPD_OPTS="$NTPD_OPTS -u ntpsec:ntpsec"

LOCKFILE=/run/lock/ntpsec-ntpdate

# MOS custom: Set permissions
set_permissions() {
  mkdir -p /var/lib/ntpsec 2>/dev/null
  chown ntpsec:ntpsec /var/lib/ntpsec
  chmod 755 /var/lib/ntpsec
}

# MOS custom: inject pools from system.json to ntp.conf
inject_pools() {
  SYSTEM_JSON=$(jq -r '.' /boot/config/system.json)
  MODE=$(echo "$SYSTEM_JSON" | jq -r '.ntp.mode')
  for server in $(echo "$SYSTEM_JSON" | jq -r '.ntp.servers[]') ; do
    echo "pool $server $MODE" >> /etc/ntpsec/ntp.conf
  done
}

# MOS custom: remove pools from ntp.conf
remove_pools() {
  sed -i '/^pool /d' /etc/ntpsec/ntp.conf
}

case $1 in
  start)
    log_daemon_msg "Starting NTP server" "ntpd"
    inject_pools
    set_permissions
    # MOS Custom
    (
      flock -w 180 9
      # shellcheck disable=SC2086
      start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON -- -p $PIDFILE $NTPD_OPTS >/dev/null 2>&1
    ) 9>$LOCKFILE
    log_end_msg $?
  ;;
  stop)
    log_daemon_msg "Stopping NTP server" "ntpd"
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --retry=TERM/30/KILL/5 --exec $DAEMON
    log_end_msg $?
    remove_pools
    rm -f $PIDFILE
  ;;
  restart|force-reload)
    $0 stop && sleep 2 && $0 start
  ;;
  try-restart)
    if $0 status >/dev/null; then
      $0 restart
    else
      exit 0
    fi
  ;;
  reload)
    exit 3
  ;;
  status)
    status_of_proc $DAEMON "NTP server"
  ;;
  *)
    echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
    exit 2
  ;;
esac
