#!/bin/sh

### BEGIN INIT INFO
# Provides:          tailscale
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts tailscaled
# Description:       starts tailscaled using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON="/usr/sbin/tailscaled"
ARGS="-statedir=/boot/config/system/tailscale_state"
NAME="tailscale"
DESC="tailscaled"
USER="root"

PID="/run/tailscale.pid"
TAILSCALE_CONFIG=$(jq '.services.tailscale' /boot/config/network.json)

. /lib/init/vars.sh
. /lib/lsb/init-functions

# Import MOS functions
. /usr/local/lib/functions/mos-common

# Set Architecture
if [ "$(get_arch)" == "amd64" ] ; then
  ARCH="amd64"
elif [ "$(get_arch)" == "arm64" ] ; then
  ARCH="arm64"
fi

# Update check
update_check() {
  if [ ! -d /boot/optional/plugins/tailscale ] ; then
    mkdir -p /boot/optional/plugins/tailscale
  fi
  if [ ! -d /boot/config/system/tailscale_state ] ; then
    mkdir -p /boot/config/system/tailscale_state
  fi
  available_version=$(ls -1 /boot/optional/plugins/tailscale | cut -d '-' -f2- | sed 's/\.tgz$//' | sort -V | tail -1)
  version_update="false"
  if [ "$(echo "$TAILSCALE_CONFIG" | jq -r '.update_check')" = "true" ] ; then
    TAILSCALE_JSON=$(wget -qO- https://pkgs.tailscale.com/stable/?mode=json)
    latest_version=$(echo "$TAILSCALE_JSON" | jq -r '.TarballsVersion')
  fi
  if [ -z "$available_version" ] ; then
    if [ -z "$TAILSCALE_JSON" ] ; then
      TAILSCALE_JSON=$(wget -qO- https://pkgs.tailscale.com/stable/?mode=json)
      latest_version=$(echo "$TAILSCALE_JSON" | jq -r '.TarballsVersion')
    fi
    if [ -z "$latest_version" ] ; then
      exit 1
    fi
    if ! wget -q -O /boot/optional/plugins/tailscale/tailscale-$latest_version.tgz https://pkgs.tailscale.com/stable/$(echo "$TAILSCALE_JSON" | jq -r --arg arch "$ARCH" '.Tarballs[$arch]') ; then
      rm -f /boot/optional/plugins/tailscale/tailscale-$latest_version.tgz
      exit 1
    fi
  elif [ "$(echo "$TAILSCALE_CONFIG" | jq -r '.update_check')" = "true" ] && [ "$available_version" != "$latest_version" ] ; then
    if ! wget -q -O /boot/optional/plugins/tailscale/tailscale-$latest_version.tgz https://pkgs.tailscale.com/stable/$(echo "$TAILSCALE_JSON" | jq -r --arg arch "$ARCH" '.Tarballs[$arch]') ; then
      rm -f /boot/optional/plugins/tailscale/tailscale-$latest_version.tgz
      latest_version=$available_version
    fi
  else
    latest_version=$available_version
  fi
  tar -C /usr/sbin --strip-components=1 -xf /boot/optional/plugins/tailscale/tailscale-$latest_version.tgz tailscale_${latest_version}_${ARCH}/tailscaled tailscale_${latest_version}_${ARCH}/tailscale
  rm -f $(ls /boot/optional/plugins/tailscale/tailscale-*.tgz 2>/dev/null | grep -v "${latest_version}")
}

# MOS custom: Start Tailscale
start_tailscale() {
  tailscaled_params=$(echo "$TAILSCALE_CONFIG" | jq -r '.tailscaled_params')
  if [ "$tailscaled_params" != "null" ] && [ "$tailscaled_params" != "" ] ; then
    ARGS="$ARGS $tailscaled_params"
  fi
  start-stop-daemon --start --background --make-pidfile --pidfile $PID --user $USER --exec "$DAEMON" -- $ARGS >/dev/null 2>&1
}

# MOS custom: Stop Tailscale
stop_tailscale() {
  start-stop-daemon --stop --pidfile "$PID"
}

case "$1" in
  start)
    log_daemon_msg "Starting $NAME" "$DESC"
    update_check
    start_tailscale
    case "$?" in
      0|1) log_end_msg 0 ;;
      2)   log_end_msg 1 ;;
    esac
  ;;
  stop)
    log_daemon_msg "Stopping $NAME" "$DESC"
    stop_tailscale
    case "$?" in
      0|1) log_end_msg 0 ;;
      2)   log_end_msg 1 ;;
    esac
  ;;
  restart)
    log_daemon_msg "Restarting $NAME" "$DESC"

    stop_tailscale
    case "$?" in
      0|1)
        update_check
        start_tailscale
        case "$?" in
          0) log_end_msg 0; check_admin ;;
          1) log_end_msg 1 ;; # Old process is still running
          *) log_end_msg 1 ;; # Failed to start
        esac
      ;;
      *)
        # Failed to stop
        log_end_msg 1
      ;;
    esac
  ;;
  status)
    status_of_proc -p $PID "$DAEMON" "$NAME" && exit 0 || exit $?
  ;;
  *)
    echo "Usage: $NAME {start|stop|restart|status}" >&2
    exit 3
  ;;
esac
