#!/bin/sh
### BEGIN INIT INFO
# Provides:          tgtd tgt
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      zfs
# Should-Stop:       zfs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: iscsi target daemon
# Description:       iscsi target daemon
### END INIT INFO

DESC="target framework daemon"
NAME=tgtd
DAEMON=/usr/sbin/${NAME}
PIDFILE=/run/${NAME}.pid

TGTD_CONFIG=/etc/tgt/targets.conf

. /lib/lsb/init-functions

[ -x $DAEMON ] || exit 0

# MOS Custom: Get json and if there should be any configured Targets
TARGET_JSON=$(jq '.' /boot/config/system/iscsi/target.json)
TARGETS_CONFIGURED=$(tgtadm -C 0 --op show --mode target 2>/dev/null | grep -E "^Target [0-9]+: " | cut -d ':' -f1 | cut -d ' ' -f2)

# MOS Custom: Configure Target
configure_target() {
  tgtadm --lld iscsi --op new --mode target --tid $1 -T $2
}

# MOS Custom: Create LUN
create_lun() {
  tgtadm --lld iscsi --op new --mode $3 --tid $1 --lun $2 -b $4
}

# MOS Custom: Update LUN
update_lun() {
  tgtadm --lld iscsi --op update --mode $3 --tid $1 --lun $2 --params $4
}

# MOS Custom: Create bindings
create_bindings() {
  tgtadm --lld iscsi --op bind --mode target --tid $1 -Q $2
  tgtadm --lld iscsi --op bind --mode target --tid $1 -I ALL
}

# MOS Custom: Remove target if somehow exists
remove_target() {
  tgtadm --mode target --op delete --tid=$1
}

# MOS Custom: Create Target
create_target() {
  TARGET_CONFIG=$(echo "$TARGET_JSON" | jq -r ".[] | select(.id == $1)")
  IQN=$(echo "$TARGET_CONFIG" | jq -r ".iqn")
  configure_target "$1" "$IQN"
  LUNS=$(echo "$TARGET_CONFIG" | jq -r ".luns[].id")
  for lun_id in $LUNS ; do
    LUN_CONFIG=$(echo "$TARGET_CONFIG" | jq -r ".luns[] | select(.id == $lun_id)")
    LUN_MODE=$(echo "$LUN_CONFIG" | jq -r '.mode')
    LUN_PATH=$(echo "$LUN_CONFIG" | jq -r '.path')
    LUN_RW_MODE=$(echo "$LUN_CONFIG" | jq -r '.backing_store')
    create_lun "$1" "$lun_id" "$LUN_MODE" "$LUN_PATH"
    if [ "$LUN_RW_MODE" = "ro" ] ; then
      update_lun "$1" "$lun_id" "$LUN_MODE" "readonly=1"
    fi
  done
  ALLOWED_INITIATORS=$(echo "$TARGET_CONFIG" | jq -r ".initiators[].iqn")
  for allowed_initiator in $ALLOWED_INITIATORS ; do
    create_bindings "$1" "$allowed_initiator"
  done
}

start()
{
  log_daemon_msg "Starting $DESC" "$NAME"
  # Start tgtd first.
  if ! start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE \
    --make-pidfile --background --exec $DAEMON -- -f ; then
    log_end_msg 1
    exit 1
  fi

  # MOS Custom: Wait 1 second to give service time to start up
  sleep 1

  log_end_msg 0
  # Put tgtd into "offline" state until all the targets are configured.
  # We don't want initiators to (re)connect and fail the connection
  # if it's not ready.
  tgtadm --op update --mode sys --name State -v offline
  # MOS Custom: Configure Targets:
  TARGET_IDS=$(echo "$TARGET_JSON" | jq -r '.[].id')
  if [ ! -z "$TARGET_IDS" ] && [ "$TARGET_IDS" != "null" ] ; then
    IFS=$'\n'
    for target_id in $TARGET_IDS ; do
      if ! echo "$TARGETS_CONFIGURED" | grep -q "^$target_id$" ; then
        create_target "$target_id"
      else
        remove_target "$target_id"
        create_target "$target_id"
      fi
    done
  fi
  # Put tgtd into "ready" state.
  tgtadm --op update --mode sys --name State -v ready
}

stop()
{
  # NOTE: Forced shutdown of the iscsi target may cause data corruption
  # for initiators that are connected.
  log_daemon_msg "Force-stopping $DESC" "$NAME"
  # Offline everything first. May be needed if we're rebooting, but
  # expect the initiators to reconnect cleanly when we boot again
  # (i.e. we don't want them to reconnect to a tgtd which is still
  # working, but the target is gone).
  tgtadm --op update --mode sys --name State -v offline >/dev/null 2>&1
  RETVAL=$?
  if [ "$RETVAL" -eq 107 ] ; then
    # tgtd not running
    log_end_msg 0
  else
    tgt-admin --offline ALL
    # Remove all targets, even if they are still in use.
    tgt-admin --update ALL -c /dev/null -f
    # It will shut down tgtd only after all targets were removed.
    tgtadm --op delete --mode system
    RETVAL=$?
    if [ "$RETVAL" -ne 0 ] ; then
      log_end_msg 1
      echo "Failed to shutdown tgtd"
      exit 1
    fi
    log_end_msg 0
    rm -f $PIDFILE
  fi
}

reload()
{
  log_daemon_msg "Reloading configuration of $DESC" "$NAME"
  # Update configuration for targets. Only targets which
  # are not in use will be updated.
  tgt-admin --update ALL -c $TGTD_CONFIG >/dev/null 2>&1
  RETVAL=$?
  if [ "$RETVAL" -eq 107 ] ; then
    log_end_msg 1
    echo "tgtd is not running"
    exit 1
  fi
  log_end_msg 0
}

forcedreload()
{
  log_daemon_msg "Forced-reload configuration of $DESC" "$NAME"
  # Update configuration for targets, even those in use.
  tgt-admin --update ALL -f -c $TGTD_CONFIG >/dev/null 2>&1
  RETVAL=$?
  if [ "$RETVAL" -eq 107 ] ; then
    log_end_msg 1
    echo "tgtd is not running"
    exit 1
  else
    log_end_msg 0
  fi
}

case $1 in
  start)
    start
  ;;
  stop|forcedstop)
    stop
  ;;
  restart|forcedrestart)
    stop && start
  ;;
  reload)
    reload
  ;;
  force-reload)
    forcedreload
  ;;
  status)
    status_of_proc -p $PIDFILE /usr/sbin/tgtd tgtd
    exit $?
  ;;
  *)
    echo "Usage: $0 {start|stop|forcedstop|restart|forcedrestart|reload|force-reload|status}"
    exit 2
  ;;
esac

